services:
  bot:
    image: ghcr.io/jmartin516/agente_preguntas_comunes_realtyplus:latest
    container_name: realtyplus_bot

    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
